import type { App } from "vue";
import "@xiaoye/theme";
export type { ComponentSize, ComponentStatus, SelectOption } from "@xiaoye/utils";
export type { CardProps, CardShadow, CardVariant } from "@xiaoye/components";
import {
  XyAffix,
  XyAlert,
  XyMessage,
  XyNotification,
  XyNotificationService,
  XyAnchor,
  XyAnchorLink,
  XyBacktop,
  XyMenu,
  XyMenuItem,
  XyMenuItemGroup,
  XySubMenu,
  XyButton,
  XyButtonGroup,
  XyBadge,
  XyAvatar,
  XyAvatarGroup,
  XyBreadcrumb,
  XyBreadcrumbItem,
  XyImage,
  XyCard,
  XyCarousel,
  XyCarouselItem,
  XyCol,
  XyConfigProvider,
  XyDatePicker,
  XyTimeSelect,
  XyDrawer,
  XyDivider,
  XyLoading,
  XyDropdown,
  XyDropdownMenu,
  XyDropdownItem,
  XyCollapse,
  XyCollapseItem,
  XyCollapseTransition,
  XyEmpty,
  XyIcon,
  XyCheckbox,
  XyCheckboxButton,
  XyCheckboxGroup,
  XyInput,
  XySwitch,
  XyInputTag,
  XyInputNumber,
  XyRate,
  XySlider,
  XyProgress,
  XyStep,
  XySteps,
  XyStatistic,
  XyCountdown,
  XyTimeline,
  XyTimelineGroup,
  XyTimelineItem,
  XySkeleton,
  XySkeletonItem,
  XyScheduler,
  XyTimePicker,
  XyLink,
  XyDialog,
  XyPagination,
  XyPopover,
  XyPopconfirm,
  XyRadio,
  XyRadioButton,
  XyRadioGroup,
  XyResult,
  XyRow,
  XyScrollbar,
  XySelect,
  XySplitter,
  XySplitterPanel,
  XySpace,
  XyTable,
  XyTableColumn,
  XyTree,
  XyTabs,
  XyTag,
  XyText,
  XyTooltip,
  XyUpload,
  XyForm,
  XyFormItem
} from "@xiaoye/components";

const INSTALL_KEY = Symbol.for("xiaoye-components:installed");

const components = [
  XyAffix,
  XyAlert,
  XyMessage,
  XyNotification,
  XyNotificationService,
  XyAnchor,
  XyAnchorLink,
  XyBacktop,
  XyMenu,
  XyMenuItem,
  XyMenuItemGroup,
  XySubMenu,
  XyButton,
  XyButtonGroup,
  XyBadge,
  XyAvatar,
  XyAvatarGroup,
  XyBreadcrumb,
  XyBreadcrumbItem,
  XyImage,
  XyCard,
  XyCarousel,
  XyCarouselItem,
  XyCol,
  XyConfigProvider,
  XyDatePicker,
  XyTimeSelect,
  XyDrawer,
  XyDivider,
  XyLoading,
  XyDropdown,
  XyDropdownMenu,
  XyDropdownItem,
  XyCollapse,
  XyCollapseItem,
  XyCollapseTransition,
  XyEmpty,
  XyIcon,
  XyCheckbox,
  XyCheckboxButton,
  XyCheckboxGroup,
  XyInput,
  XySwitch,
  XyInputTag,
  XyInputNumber,
  XyRate,
  XySlider,
  XyProgress,
  XyStep,
  XySteps,
  XyStatistic,
  XyCountdown,
  XyTimeline,
  XyTimelineGroup,
  XyTimelineItem,
  XySkeleton,
  XySkeletonItem,
  XyScheduler,
  XyTimePicker,
  XyLink,
  XyDialog,
  XyPagination,
  XyPopover,
  XyPopconfirm,
  XyRadio,
  XyRadioButton,
  XyRadioGroup,
  XyResult,
  XyRow,
  XyScrollbar,
  XySelect,
  XySplitter,
  XySplitterPanel,
  XySpace,
  XyTable,
  XyTableColumn,
  XyTree,
  XyTabs,
  XyTag,
  XyText,
  XyTooltip,
  XyUpload,
  XyForm,
  XyFormItem
];

export function install(app: App) {
  const appWithInstallFlag = app as App & {
    [INSTALL_KEY]?: boolean;
  };

  if (appWithInstallFlag[INSTALL_KEY]) {
    return;
  }

  appWithInstallFlag[INSTALL_KEY] = true;

  components.forEach((component) => {
    app.use(component);
  });
}

export {
  XyAffix,
  XyAlert,
  XyMessage,
  XyNotification,
  XyNotificationService,
  XyAnchor,
  XyAnchorLink,
  XyBacktop,
  XyMenu,
  XyMenuItem,
  XyMenuItemGroup,
  XySubMenu,
  XyButton,
  XyButtonGroup,
  XyBadge,
  XyAvatar,
  XyAvatarGroup,
  XyBreadcrumb,
  XyBreadcrumbItem,
  XyImage,
  XyCard,
  XyCarousel,
  XyCarouselItem,
  XyCol,
  XyConfigProvider,
  XyDatePicker,
  XyTimeSelect,
  XyDrawer,
  XyDivider,
  XyLoading,
  XyDropdown,
  XyDropdownMenu,
  XyDropdownItem,
  XyCollapse,
  XyCollapseItem,
  XyCollapseTransition,
  XyEmpty,
  XyIcon,
  XyCheckbox,
  XyCheckboxButton,
  XyCheckboxGroup,
  XyInput,
  XySwitch,
  XyInputTag,
  XyInputNumber,
  XyRate,
  XySlider,
  XyProgress,
  XyStep,
  XySteps,
  XyStatistic,
  XyCountdown,
  XyTimeline,
  XyTimelineGroup,
  XyTimelineItem,
  XySkeleton,
  XySkeletonItem,
  XyScheduler,
  XyTimePicker,
  XyLink,
  XyDialog,
  XyPagination,
  XyPopover,
  XyPopconfirm,
  XyRadio,
  XyRadioButton,
  XyRadioGroup,
  XyResult,
  XyRow,
  XyScrollbar,
  XySelect,
  XySplitter,
  XySplitterPanel,
  XySpace,
  XyTable,
  XyTableColumn,
  XyTree,
  XyTabs,
  XyTag,
  XyText,
  XyTooltip,
  XyUpload,
  XyForm,
  XyFormItem
};

export * from "@xiaoye/components";

declare module "vue" {
  interface ComponentCustomProperties {
    $loading?: typeof import("@xiaoye/components").XyLoadingService;
    $message?: typeof import("@xiaoye/components").XyMessage;
    $notify?: typeof import("@xiaoye/components").XyNotificationService;
  }
}

export default {
  install
};
