import Table from "./src/table.vue";
import TableColumn from "./src/table-column.vue";
import type { SFCWithInstall } from "@xiaoye/primitives";
import { withInstall } from "@xiaoye/primitives";
import type {
  TableAlign,
  TableCellClassName,
  TableCellMouseHandler,
  TableCellSlotProps,
  TableCellStyle,
  TableBodyRow,
  TableColumnFixed,
  TableColumnProps,
  TableColumnType,
  TableCurrentChangeHandler,
  TableCurrentRowKeyChangeHandler,
  TableExpandSlotProps,
  TableExpandChangeHandler,
  TableExpandRowKeysChangeHandler,
  TableFilterChangeHandler,
  TableFilterOption,
  TableFilterIconSlotProps,
  TableFilterValue,
  TableFilterValues,
  TableFilterValuesChangeHandler,
  TableHeaderDragendHandler,
  TableHeaderSlotProps,
  TableHeaderCell,
  TableHeaderCellClassName,
  TableHeaderCellStyle,
  TableHeaderMouseHandler,
  TableHeaderRowClassName,
  TableHeaderRowStyle,
  TableInstance,
  TableLayout,
  TableOverflowTooltip,
  TableOverflowTooltipOptions,
  TableProps,
  TableResolvedColumn,
  TableRowClickHandler,
  TableRowClassName,
  TableRowKey,
  TableRowMouseHandler,
  TableRowStyle,
  TableSection,
  TableSelectHandler,
  TableSelectionChangeHandler,
  TableSummaryMethodContext,
  TableSummaryValue,
  TableScrollPayload,
  TableSortChangePayload,
  TableSortOrder,
  TableSortOrderChangeHandler,
  TableSortPropChangeHandler,
  TableSortState,
  TableSortable,
  TableSpanMethodContext,
  TableSpanResult,
  TableTooltipFormatterContext,
  TableTreeNode,
  TableTreeProps
} from "./src/table";

export type {
  TableAlign,
  TableCellClassName,
  TableCellMouseHandler,
  TableCellSlotProps,
  TableCellStyle,
  TableBodyRow,
  TableColumnFixed,
  TableColumnProps,
  TableColumnType,
  TableCurrentChangeHandler,
  TableCurrentRowKeyChangeHandler,
  TableExpandSlotProps,
  TableExpandChangeHandler,
  TableExpandRowKeysChangeHandler,
  TableFilterChangeHandler,
  TableFilterOption,
  TableFilterIconSlotProps,
  TableFilterValue,
  TableFilterValues,
  TableFilterValuesChangeHandler,
  TableHeaderDragendHandler,
  TableHeaderSlotProps,
  TableHeaderCell,
  TableHeaderCellClassName,
  TableHeaderCellStyle,
  TableHeaderMouseHandler,
  TableHeaderRowClassName,
  TableHeaderRowStyle,
  TableInstance,
  TableLayout,
  TableOverflowTooltip,
  TableOverflowTooltipOptions,
  TableProps,
  TableResolvedColumn,
  TableRowClickHandler,
  TableRowClassName,
  TableRowKey,
  TableRowMouseHandler,
  TableRowStyle,
  TableSection,
  TableSelectHandler,
  TableSelectionChangeHandler,
  TableSummaryMethodContext,
  TableSummaryValue,
  TableScrollPayload,
  TableSortChangePayload,
  TableSortOrder,
  TableSortOrderChangeHandler,
  TableSortPropChangeHandler,
  TableSortState,
  TableSortable,
  TableSpanMethodContext,
  TableSpanResult,
  TableTooltipFormatterContext,
  TableTreeNode,
  TableTreeProps
};

export const XyTableColumn = withInstall(TableColumn, "xy-table-column");

export const XyTable = withInstall(Table, "xy-table") as SFCWithInstall<typeof Table> & {
  Column: typeof XyTableColumn;
};

XyTable.Column = XyTableColumn;

export default XyTable;
