// 此文件由 scripts/generate-tokens.mjs 从 tokens.css 自动生成，不要手工编辑。

/** 刻度层令牌（与主题无关） */
export const scaleTokens = {
  "fontFamilyBase": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", \"SF Pro Text\", \"Helvetica Neue\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", \"Source Han Sans SC\", Arial, sans-serif",
  "fontFamilyCode": "\"SF Mono\", \"Source Code Pro\", SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace",
  "fontSize2xs": "11px",
  "fontSizeXs": "12px",
  "fontSizeSm": "13px",
  "fontSizeMd": "14px",
  "fontSizeLg": "16px",
  "fontSizeXl": "20px",
  "fontSize2xl": "26px",
  "fontSize3xl": "32px",
  "fontSize4xl": "48px",
  "fontWeightLight": "300",
  "fontWeightRegular": "400",
  "fontWeightMedium": "500",
  "fontWeightSemibold": "600",
  "lineHeightTight": "1.2",
  "lineHeight": "1.5",
  "radiusXs": "2px",
  "radiusSm": "3px",
  "radiusMd": "4px",
  "radiusLg": "6px",
  "radiusXl": "8px",
  "radiusPill": "999px",
  "space1": "4px",
  "space2": "8px",
  "space3": "12px",
  "space4": "16px",
  "space5": "20px",
  "space6": "24px",
  "space7": "32px",
  "transitionDurationFast": "0.15s",
  "transitionDurationNormal": "0.25s",
  "transitionDurationSlow": "0.4s",
  "transitionTiming": "cubic-bezier(0.4, 0, 0.2, 1)",
  "transitionTimingIn": "cubic-bezier(0.4, 0, 1, 1)",
  "transitionTimingOut": "cubic-bezier(0, 0, 0.2, 1)",
  "mixLight": "#ffffff",
} as const;
