import { primitiveTokens } from "./primitives";

export const semanticTokens = {
  colorPrimary: primitiveTokens.color.brand["500"],
  colorPrimaryHover: primitiveTokens.color.brand["600"],
  colorPrimaryActive: primitiveTokens.color.brand["700"],
  colorPrimarySoft: primitiveTokens.color.brand["50"],
  colorPrimarySoftHover: primitiveTokens.color.brand["100"],
  colorSuccess: primitiveTokens.color.success,
  colorSuccessHover: primitiveTokens.color.green["600"],
  colorSuccessActive: primitiveTokens.color.green["700"],
  colorSuccessSoft: primitiveTokens.color.green["50"],
  colorSuccessSoftHover: primitiveTokens.color.green["100"],
  colorWarning: primitiveTokens.color.warning,
  colorWarningHover: primitiveTokens.color.amber["600"],
  colorWarningActive: primitiveTokens.color.amber["700"],
  colorWarningSoft: primitiveTokens.color.amber["50"],
  colorWarningSoftHover: primitiveTokens.color.amber["100"],
  colorDanger: primitiveTokens.color.danger,
  colorDangerHover: primitiveTokens.color.red["600"],
  colorDangerActive: primitiveTokens.color.red["700"],
  colorDangerSoft: primitiveTokens.color.red["50"],
  colorDangerSoftHover: primitiveTokens.color.red["100"],
  colorText: primitiveTokens.color.ink["900"],
  colorTextHeading: primitiveTokens.color.ink["900"],
  colorTextSecondary: primitiveTokens.color.ink["600"],
  colorTextSubtle: primitiveTokens.color.ink["500"],
  colorTextMuted: primitiveTokens.color.ink["500"],
  colorBorder: primitiveTokens.color.ink["200"],
  colorBorderStrong: primitiveTokens.color.ink["300"],
  colorBorderSubtle: primitiveTokens.color.ink["100"],
  colorBg: "#ffffff",
  colorBgMuted: primitiveTokens.color.ink["50"],
  colorBgSubtle: "#fbfcfe",
  colorBgElevated: "#fdfdff",
  colorBgFloating: "#ffffff",
  colorSurfaceRaised: "#fdfdff",
  colorSurfaceSunken: primitiveTokens.color.ink["50"],
  colorOverlay: "rgba(28, 28, 30, 0.42)",
  colorFocusRing: "rgba(91, 118, 254, 0.22)",
  radius: primitiveTokens.radius.md,
  radiusControl: primitiveTokens.radius.md,
  radiusContainer: primitiveTokens.radius.lg,
  radiusOverlay: primitiveTokens.radius.xl,
  fontSize: primitiveTokens.fontSize.md,
  fontSizeControl: primitiveTokens.fontSize.md,
  fontSizeBody: primitiveTokens.fontSize.md,
  fontSizeTitle: primitiveTokens.fontSize.xl,
  shadow: primitiveTokens.shadow.md,
  shadowCard: primitiveTokens.shadow.card,
  shadowPopup: primitiveTokens.shadow.popup,
  shadowModal: primitiveTokens.shadow.modal
} as const;
