import type { DefaultTheme } from "vitepress";

export const columnSidebar: DefaultTheme.Sidebar = [
  {
    text: "架构篇",
    collapsed: false,
    items: [
      { text: "01 项目全景", link: "/column/guide/01-architecture-overview" },
      { text: "02 Primitives 设计", link: "/column/guide/02-primitives-design" },
      { text: "03 主题令牌", link: "/column/guide/03-theme-tokens" },
      { text: "04 组件注册", link: "/column/guide/04-component-registration" },
      { text: "05 构建与发布", link: "/column/guide/05-build-and-release" },
      { text: "06 测试体系", link: "/column/guide/06-testing" },
      { text: "07 文档站架构", link: "/column/guide/07-docs-site" },
      { text: "08 MCP Server", link: "/column/guide/08-mcp-server" },
      { text: "09 AI 协作开发", link: "/column/guide/09-ai-collaboration" },
    ],
  },
  {
    text: "基础组件 · basic 组",
    collapsed: true,
    items: [
      { text: "10 Button 按钮", link: "/column/components/10-button" },
      { text: "11 Link 链接", link: "/column/components/11-link" },
      { text: "12 Breadcrumb 面包屑", link: "/column/components/12-breadcrumb" },
      { text: "13 Text 文本", link: "/column/components/13-text" },
      { text: "14 Badge 徽标", link: "/column/components/14-badge" },
      { text: "15 Avatar 头像", link: "/column/components/15-avatar" },
      { text: "16 Image 图片", link: "/column/components/16-image" },
      { text: "17 Watermark 水印", link: "/column/components/17-watermark" },
      { text: "18 Card 卡片", link: "/column/components/18-card" },
      { text: "19 CheckCard 选择卡片", link: "/column/components/19-check-card" },
      { text: "20 Carousel 走马灯", link: "/column/components/20-carousel" },
      { text: "21 Affix 固钉", link: "/column/components/21-affix" },
      { text: "22 Anchor 锚点", link: "/column/components/22-anchor" },
      { text: "23 Menu 菜单", link: "/column/components/23-menu" },
      { text: "24 Row 栅格-行", link: "/column/components/24-row" },
      { text: "25 Col 栅格-列", link: "/column/components/25-col" },
      { text: "26 Divider 分割线", link: "/column/components/26-divider" },
      { text: "27 Space 间距", link: "/column/components/27-space" },
      { text: "28 Scrollbar 滚动条", link: "/column/components/28-scrollbar" },
      { text: "29 Splitter 分割面板", link: "/column/components/29-splitter" },
      { text: "30 Icon 图标", link: "/column/components/30-icon" },
      { text: "31 Tag 标签", link: "/column/components/31-tag" },
      { text: "32 Tabs 标签页", link: "/column/components/32-tabs" },
    ],
  },
  {
    text: "基础组件 · form 组",
    collapsed: true,
    items: [
      { text: "33 ConfigProvider 全局配置", link: "/column/components/33-config-provider" },
      { text: "34 Input 输入框", link: "/column/components/34-input" },
      { text: "35 AutoComplete 自动完成", link: "/column/components/35-auto-complete" },
      { text: "36 Cascader 级联选择", link: "/column/components/36-cascader" },
      { text: "37 Radio 单选", link: "/column/components/37-radio" },
      { text: "38 Checkbox 复选", link: "/column/components/38-checkbox" },
      { text: "39 Switch 开关", link: "/column/components/39-switch" },
      { text: "40 InputTag 标签输入", link: "/column/components/40-input-tag" },
      { text: "41 InputNumber 数字输入", link: "/column/components/41-input-number" },
      { text: "42 Rate 评分", link: "/column/components/42-rate" },
      { text: "43 Slider 滑块", link: "/column/components/43-slider" },
      { text: "44 DatePicker 日期选择", link: "/column/components/44-date-picker" },
      { text: "45 TimePicker 时间选择", link: "/column/components/45-time-picker" },
      { text: "46 TimeSelect 时间选择器", link: "/column/components/46-time-select" },
      { text: "47 Select 选择器", link: "/column/components/47-select" },
      { text: "48 TreeSelect 树选择", link: "/column/components/48-tree-select" },
      { text: "49 Form 表单", link: "/column/components/49-form" },
      { text: "50 Upload 上传", link: "/column/components/50-upload" },
      { text: "51 Editor 编辑器", link: "/column/components/51-editor" },
    ],
  },
  {
    text: "基础组件 · feedback 组",
    collapsed: true,
    items: [
      { text: "52 Alert 警告", link: "/column/components/52-alert" },
      { text: "53 Message 消息提示", link: "/column/components/53-message" },
      { text: "54 Notification 通知", link: "/column/components/54-notification" },
      { text: "55 Backtop 回到顶部", link: "/column/components/55-backtop" },
      { text: "56 Collapse 折叠面板", link: "/column/components/56-collapse" },
      { text: "57 Empty 空状态", link: "/column/components/57-empty" },
      { text: "58 Loading 加载", link: "/column/components/58-loading" },
      { text: "59 Skeleton 骨架屏", link: "/column/components/59-skeleton" },
      { text: "60 Result 结果", link: "/column/components/60-result" },
      { text: "61 Tooltip 文字提示", link: "/column/components/61-tooltip" },
      { text: "62 Popover 弹出框", link: "/column/components/62-popover" },
      { text: "63 Popconfirm 确认弹出", link: "/column/components/63-popconfirm" },
      { text: "64 Dropdown 下拉菜单", link: "/column/components/64-dropdown" },
      { text: "65 Transfer 穿梭框", link: "/column/components/65-transfer" },
      { text: "66 Dialog 对话框", link: "/column/components/66-dialog" },
      { text: "67 Drawer 抽屉", link: "/column/components/67-drawer" },
      { text: "68 CollapseTransition 折叠过渡", link: "/column/components/68-collapse-transition" },
    ],
  },
  {
    text: "基础组件 · data 组",
    collapsed: true,
    items: [
      { text: "69 Statistic 统计数值", link: "/column/components/69-statistic" },
      { text: "70 Countdown 倒计时", link: "/column/components/70-countdown" },
      { text: "71 Progress 进度条", link: "/column/components/71-progress" },
      { text: "72 Steps 步骤条", link: "/column/components/72-steps" },
      { text: "73 Timeline 时间线", link: "/column/components/73-timeline" },
      { text: "74 Scheduler 日程", link: "/column/components/74-scheduler" },
      { text: "75 Descriptions 描述列表", link: "/column/components/75-descriptions" },
      { text: "76 Tree 树形控件", link: "/column/components/76-tree" },
      { text: "77 Table 表格", link: "/column/components/77-table" },
      { text: "78 Pagination 分页", link: "/column/components/78-pagination" },
      { text: "79 Charts 图表", link: "/column/components/79-charts" },
      { text: "80 AudioPlayer 音频播放", link: "/column/components/80-audio-player" },
      { text: "81 VideoPlayer 视频播放", link: "/column/components/81-video-player" },
    ],
  },
  {
    text: "Pro 组件 · form 组",
    collapsed: true,
    items: [
      { text: "82 SearchForm 搜索表单", link: "/column/pro-components/82-search-form" },
      { text: "83 ProForm 增强表单", link: "/column/pro-components/83-pro-form" },
      { text: "84 OverlayForm 浮层表单", link: "/column/pro-components/84-overlay-form" },
      { text: "85 DialogForm 弹窗表单", link: "/column/pro-components/85-dialog-form" },
      { text: "86 DrawerForm 抽屉表单", link: "/column/pro-components/86-drawer-form" },
      { text: "87 StepsForm 分步表单", link: "/column/pro-components/87-steps-form" },
      { text: "88 FilterPanel 筛选面板", link: "/column/pro-components/88-filter-panel" },
      { text: "89 RequestForm 请求表单", link: "/column/pro-components/89-request-form" },
      { text: "90 LoginForm 登录表单", link: "/column/pro-components/90-login-form" },
    ],
  },
  {
    text: "Pro 组件 · data 组",
    collapsed: true,
    items: [
      { text: "91 ProTable 增强表格", link: "/column/pro-components/91-pro-table" },
      { text: "92 ColumnSettingPanel 列设置面板", link: "/column/pro-components/92-column-setting-panel" },
      { text: "93 SavedViewTabs 视图页签", link: "/column/pro-components/93-saved-view-tabs" },
      { text: "94 TableFilterDrawer 表格筛选抽屉", link: "/column/pro-components/94-table-filter-drawer" },
      { text: "95 ImportResultTable 导入结果表格", link: "/column/pro-components/95-import-result-table" },
    ],
  },
  {
    text: "Pro 组件 · detail 组",
    collapsed: true,
    items: [
      { text: "96 AuditTimeline 审计时间线", link: "/column/pro-components/96-audit-timeline" },
      { text: "97 DetailPanel 详情承载面板", link: "/column/pro-components/97-detail-panel" },
      { text: "98 DetailPage 详情页面", link: "/column/pro-components/98-detail-page" },
    ],
  },
  {
    text: "Pro 组件 · page 组",
    collapsed: true,
    items: [
      { text: "99 PageToolbar 页面工具栏", link: "/column/pro-components/99-page-toolbar" },
      { text: "100 PageHeader 页面头部", link: "/column/pro-components/100-page-header" },
      { text: "101 PageContainer 页面容器", link: "/column/pro-components/101-page-container" },
      { text: "102 AvatarMenu 头像菜单", link: "/column/pro-components/102-avatar-menu" },
      { text: "103 HeaderTabs 头部页签", link: "/column/pro-components/103-header-tabs" },
      { text: "104 NoticeCenter 站内消息中心", link: "/column/pro-components/104-notice-center" },
      { text: "105 StatCard 指标卡片", link: "/column/pro-components/105-stat-card" },
      { text: "106 AsyncStateContainer 异步状态容器", link: "/column/pro-components/106-async-state-container" },
      { text: "107 ListPage 列表页面", link: "/column/pro-components/107-list-page" },
      { text: "108 CrudPage 增删改查页面", link: "/column/pro-components/108-crud-page" },
      { text: "109 SplitLayoutPage 分栏页面", link: "/column/pro-components/109-split-layout-page" },
    ],
  },
  {
    text: "Pro 组件 · workflow 组",
    collapsed: true,
    items: [
      { text: "110 ApprovalFlowPanel 审批流面板", link: "/column/pro-components/110-approval-flow-panel" },
      { text: "111 ImportWizard 导入向导", link: "/column/pro-components/111-import-wizard" },
      { text: "112 ExportTaskPanel 导出任务面板", link: "/column/pro-components/112-export-task-panel" },
    ],
  },
];
