export const carouselTriggers = ["hover", "click"] as const;
export const carouselIndicatorPositions = ["", "none", "outside"] as const;
export const carouselArrows = ["always", "hover", "never"] as const;
export const carouselTypes = ["", "card"] as const;
export const carouselDirections = ["horizontal", "vertical"] as const;
export const carouselEffects = ["slide", "fade"] as const;
export const carouselIndicatorTypes = ["line", "dot"] as const;
export const carouselThumbPlacements = ["bottom", "top", "left", "right"] as const;
export const carouselThumbIndicatorTypes = ["thumbnail", "line", "dot"] as const;
export const carouselProgressPlacements = ["bottom", "top", "indicator"] as const;
export const carouselAlignments = ["start", "center", "end"] as const;
export const carouselContainScrolls = ["trim", "keep"] as const;

export type CarouselTrigger = (typeof carouselTriggers)[number];
export type CarouselIndicatorPosition = (typeof carouselIndicatorPositions)[number];
export type CarouselArrow = (typeof carouselArrows)[number];
export type CarouselType = (typeof carouselTypes)[number];
export type CarouselDirection = (typeof carouselDirections)[number];
export type CarouselEffect = (typeof carouselEffects)[number];
export type CarouselIndicatorType = (typeof carouselIndicatorTypes)[number];
export type CarouselThumbPlacement = (typeof carouselThumbPlacements)[number];
export type CarouselThumbIndicatorType = (typeof carouselThumbIndicatorTypes)[number];
export type CarouselProgressPlacement = (typeof carouselProgressPlacements)[number];
export type CarouselAlignment = (typeof carouselAlignments)[number];
export type CarouselContainScroll = (typeof carouselContainScrolls)[number];

export interface CarouselProps {
  activeIndex?: number;
  initialIndex?: number;
  height?: string;
  trigger?: CarouselTrigger;
  autoplay?: boolean;
  interval?: number;
  indicatorPosition?: CarouselIndicatorPosition;
  arrow?: CarouselArrow;
  type?: CarouselType;
  cardScale?: number;
  loop?: boolean;
  direction?: CarouselDirection;
  pauseOnHover?: boolean;
  draggable?: boolean;
  effect?: CarouselEffect;
  duration?: number;
  easing?: string;
  slidesPerView?: number;
  slidesPerGroup?: number;
  gap?: number | string;
  centered?: boolean;
  indicatorType?: CarouselIndicatorType;
  thumbs?: boolean;
  thumbsPlacement?: CarouselThumbPlacement;
  thumbsPerView?: number;
  thumbsGap?: number | string;
  thumbsIndicatorType?: CarouselThumbIndicatorType;
  showProgress?: boolean;
  progressPlacement?: CarouselProgressPlacement;
  progressColor?: string;
  align?: CarouselAlignment;
  containScroll?: CarouselContainScroll;
  peek?: number | string;
  lazy?: boolean;
  lazyRange?: number;
  virtual?: boolean;
  virtualBuffer?: number;
  ariaLabel?: string;
  keyboard?: boolean;
}
